trigger:
- main

pr:
- main

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.15'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'

  - script: |
      mkdir build
      cd build
      cmake .. -GXcode
    displayName: 'Generate MacOS solution'

  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'build/App.xcodeproj'
      scheme: 'App'
      sdk: 'macosx'
      useXcpretty: false
      configuration: RelWithDebInfo
    displayName: 'Build MacOS'

- job: win32_x64
  timeoutInMinutes: 30
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'

  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 16 2019" -A x64 -DBGFX_CONFIG_MEMORY_TRACKING=ON -DBGFX_CONFIG_DEBUG=ON ..
    displayName: 'Generate Win32_x64 solution'

  - task: MSBuild@1
    inputs:
      solution: 'build/App.sln'
      maximumCpuCount: true
      configuration: 'RelWithDebInfo'
    displayName: 'Build WIN32_x64'

- job: Ubuntu_Clang
  timeoutInMinutes: 30
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    CC: clang-8
    CXX: clang++-8

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'
  - script: |
      sudo apt-get update
      sudo apt-get install libgl1-mesa-dev clang-8 libc++-8-dev libc++abi-8-dev ninja-build
    displayName: 'Install packages'
  - script: |
      mkdir build
      cd build
      cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo
      ninja
    displayName: 'Build X11'

- job: Ubuntu_Emscripten
  timeoutInMinutes: 30
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'
  - script: |
      sudo apt-get update
      sudo apt-get install libgl1-mesa-dev clang-8 libc++-8-dev libc++abi-8-dev ninja-build
      git clone https://github.com/emscripten-core/emsdk.git
      ./emsdk/emsdk install latest
    displayName: 'Install packages'
  - script: |
      ./emsdk/emsdk activate latest
      source ./emsdk/emsdk_env.sh
      mkdir build
      cd build
      emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
      ninja
    displayName: 'Build Emscripten'
