// generated by CMake
#include <stdint.h>
#include <bgfx/embedded_shader.h>
#ifdef WIN32
#include "Default_vs_dx9.h"
#include "Default_vs_dx11.h"
#endif
#include "Default_vs_glsl.h"
#ifdef __APPLE__
#include "Default_vs_mtl.h"
#endif
#include "Default_vs_spv.h"
#include "Default_vs_essl.h"
#ifdef WIN32
#include "Default_fs_dx9.h"
#include "Default_fs_dx11.h"
#endif
#include "Default_fs_glsl.h"
#ifdef __APPLE__
#include "Default_fs_mtl.h"
#endif
#include "Default_fs_spv.h"
#include "Default_fs_essl.h"
